//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace ChannelAdvisorSOAP.Fulfillment {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="FulfillmentServiceSoap", Namespace="http://api.channeladvisor.com/webservices/")]
    public partial class FulfillmentService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private APICredentials aPICredentialsValueField;
        
        private System.Threading.SendOrPostCallback GetOrderFulfillmentDetailListOperationCompleted;
        
        private System.Threading.SendOrPostCallback UpdateOrderFulfillmentsOperationCompleted;
        
        private System.Threading.SendOrPostCallback CreateOrderFulfillmentsOperationCompleted;
        
        private System.Threading.SendOrPostCallback MoveFulfillmentItemsOperationCompleted;
        
        private System.Threading.SendOrPostCallback PingOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public FulfillmentService() {
            this.Timeout = global::ChannelAdvisorSOAP.Properties.Settings.Default.ChannelAdvisorSOAP_Timeout;
            this.Url = global::ChannelAdvisorSOAP.Properties.Settings.Default.ChannelAdvisorSOAP_Fulfillment_FulfillmentService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public APICredentials APICredentialsValue {
            get {
                return this.aPICredentialsValueField;
            }
            set {
                this.aPICredentialsValueField = value;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event GetOrderFulfillmentDetailListCompletedEventHandler GetOrderFulfillmentDetailListCompleted;
        
        /// <remarks/>
        public event UpdateOrderFulfillmentsCompletedEventHandler UpdateOrderFulfillmentsCompleted;
        
        /// <remarks/>
        public event CreateOrderFulfillmentsCompletedEventHandler CreateOrderFulfillmentsCompleted;
        
        /// <remarks/>
        public event MoveFulfillmentItemsCompletedEventHandler MoveFulfillmentItemsCompleted;
        
        /// <remarks/>
        public event PingCompletedEventHandler PingCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("APICredentialsValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://api.channeladvisor.com/webservices/GetOrderFulfillmentDetailList", RequestNamespace="http://api.channeladvisor.com/webservices/", ResponseNamespace="http://api.channeladvisor.com/webservices/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public APIResultOfArrayOfOrderFulfillmentResponse GetOrderFulfillmentDetailList([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string accountID, int[] orderIDList, string[] clientOrderIdentifierList) {
            object[] results = this.Invoke("GetOrderFulfillmentDetailList", new object[] {
                        accountID,
                        orderIDList,
                        clientOrderIdentifierList});
            return ((APIResultOfArrayOfOrderFulfillmentResponse)(results[0]));
        }
        
        /// <remarks/>
        public void GetOrderFulfillmentDetailListAsync(string accountID, int[] orderIDList, string[] clientOrderIdentifierList) {
            this.GetOrderFulfillmentDetailListAsync(accountID, orderIDList, clientOrderIdentifierList, null);
        }
        
        /// <remarks/>
        public void GetOrderFulfillmentDetailListAsync(string accountID, int[] orderIDList, string[] clientOrderIdentifierList, object userState) {
            if ((this.GetOrderFulfillmentDetailListOperationCompleted == null)) {
                this.GetOrderFulfillmentDetailListOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetOrderFulfillmentDetailListOperationCompleted);
            }
            this.InvokeAsync("GetOrderFulfillmentDetailList", new object[] {
                        accountID,
                        orderIDList,
                        clientOrderIdentifierList}, this.GetOrderFulfillmentDetailListOperationCompleted, userState);
        }
        
        private void OnGetOrderFulfillmentDetailListOperationCompleted(object arg) {
            if ((this.GetOrderFulfillmentDetailListCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetOrderFulfillmentDetailListCompleted(this, new GetOrderFulfillmentDetailListCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("APICredentialsValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://api.channeladvisor.com/webservices/UpdateOrderFulfillments", RequestNamespace="http://api.channeladvisor.com/webservices/", ResponseNamespace="http://api.channeladvisor.com/webservices/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public APIResultOfArrayOfFulfillmentOperationResponse UpdateOrderFulfillments([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string accountID, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] System.Nullable<int> orderID, string clientOrderIdentifier, FulfillmentUpdateSubmit[] fulfillmentUpdateList) {
            object[] results = this.Invoke("UpdateOrderFulfillments", new object[] {
                        accountID,
                        orderID,
                        clientOrderIdentifier,
                        fulfillmentUpdateList});
            return ((APIResultOfArrayOfFulfillmentOperationResponse)(results[0]));
        }
        
        /// <remarks/>
        public void UpdateOrderFulfillmentsAsync(string accountID, System.Nullable<int> orderID, string clientOrderIdentifier, FulfillmentUpdateSubmit[] fulfillmentUpdateList) {
            this.UpdateOrderFulfillmentsAsync(accountID, orderID, clientOrderIdentifier, fulfillmentUpdateList, null);
        }
        
        /// <remarks/>
        public void UpdateOrderFulfillmentsAsync(string accountID, System.Nullable<int> orderID, string clientOrderIdentifier, FulfillmentUpdateSubmit[] fulfillmentUpdateList, object userState) {
            if ((this.UpdateOrderFulfillmentsOperationCompleted == null)) {
                this.UpdateOrderFulfillmentsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUpdateOrderFulfillmentsOperationCompleted);
            }
            this.InvokeAsync("UpdateOrderFulfillments", new object[] {
                        accountID,
                        orderID,
                        clientOrderIdentifier,
                        fulfillmentUpdateList}, this.UpdateOrderFulfillmentsOperationCompleted, userState);
        }
        
        private void OnUpdateOrderFulfillmentsOperationCompleted(object arg) {
            if ((this.UpdateOrderFulfillmentsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UpdateOrderFulfillmentsCompleted(this, new UpdateOrderFulfillmentsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("APICredentialsValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://api.channeladvisor.com/webservices/CreateOrderFulfillments", RequestNamespace="http://api.channeladvisor.com/webservices/", ResponseNamespace="http://api.channeladvisor.com/webservices/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public APIResultOfArrayOfFulfillmentOperationResponse CreateOrderFulfillments([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string accountID, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] System.Nullable<int> orderID, string clientOrderIdentifier, FulfillmentCreateSubmit[] fulfillmentList) {
            object[] results = this.Invoke("CreateOrderFulfillments", new object[] {
                        accountID,
                        orderID,
                        clientOrderIdentifier,
                        fulfillmentList});
            return ((APIResultOfArrayOfFulfillmentOperationResponse)(results[0]));
        }
        
        /// <remarks/>
        public void CreateOrderFulfillmentsAsync(string accountID, System.Nullable<int> orderID, string clientOrderIdentifier, FulfillmentCreateSubmit[] fulfillmentList) {
            this.CreateOrderFulfillmentsAsync(accountID, orderID, clientOrderIdentifier, fulfillmentList, null);
        }
        
        /// <remarks/>
        public void CreateOrderFulfillmentsAsync(string accountID, System.Nullable<int> orderID, string clientOrderIdentifier, FulfillmentCreateSubmit[] fulfillmentList, object userState) {
            if ((this.CreateOrderFulfillmentsOperationCompleted == null)) {
                this.CreateOrderFulfillmentsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCreateOrderFulfillmentsOperationCompleted);
            }
            this.InvokeAsync("CreateOrderFulfillments", new object[] {
                        accountID,
                        orderID,
                        clientOrderIdentifier,
                        fulfillmentList}, this.CreateOrderFulfillmentsOperationCompleted, userState);
        }
        
        private void OnCreateOrderFulfillmentsOperationCompleted(object arg) {
            if ((this.CreateOrderFulfillmentsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CreateOrderFulfillmentsCompleted(this, new CreateOrderFulfillmentsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("APICredentialsValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://api.channeladvisor.com/webservices/MoveFulfillmentItems", RequestNamespace="http://api.channeladvisor.com/webservices/", ResponseNamespace="http://api.channeladvisor.com/webservices/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public APIResultOfArrayOfFulfillmentItemMoveResponse MoveFulfillmentItems([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string accountID, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] System.Nullable<int> orderID, string clientOrderIdentifier, int destinationFulfillmentID, FulfillmentItemSubmit[] sourceFulfillmentItemList) {
            object[] results = this.Invoke("MoveFulfillmentItems", new object[] {
                        accountID,
                        orderID,
                        clientOrderIdentifier,
                        destinationFulfillmentID,
                        sourceFulfillmentItemList});
            return ((APIResultOfArrayOfFulfillmentItemMoveResponse)(results[0]));
        }
        
        /// <remarks/>
        public void MoveFulfillmentItemsAsync(string accountID, System.Nullable<int> orderID, string clientOrderIdentifier, int destinationFulfillmentID, FulfillmentItemSubmit[] sourceFulfillmentItemList) {
            this.MoveFulfillmentItemsAsync(accountID, orderID, clientOrderIdentifier, destinationFulfillmentID, sourceFulfillmentItemList, null);
        }
        
        /// <remarks/>
        public void MoveFulfillmentItemsAsync(string accountID, System.Nullable<int> orderID, string clientOrderIdentifier, int destinationFulfillmentID, FulfillmentItemSubmit[] sourceFulfillmentItemList, object userState) {
            if ((this.MoveFulfillmentItemsOperationCompleted == null)) {
                this.MoveFulfillmentItemsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnMoveFulfillmentItemsOperationCompleted);
            }
            this.InvokeAsync("MoveFulfillmentItems", new object[] {
                        accountID,
                        orderID,
                        clientOrderIdentifier,
                        destinationFulfillmentID,
                        sourceFulfillmentItemList}, this.MoveFulfillmentItemsOperationCompleted, userState);
        }
        
        private void OnMoveFulfillmentItemsOperationCompleted(object arg) {
            if ((this.MoveFulfillmentItemsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.MoveFulfillmentItemsCompleted(this, new MoveFulfillmentItemsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("APICredentialsValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://api.channeladvisor.com/webservices/Ping", RequestNamespace="http://api.channeladvisor.com/webservices/", ResponseNamespace="http://api.channeladvisor.com/webservices/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public APIResultOfString Ping() {
            object[] results = this.Invoke("Ping", new object[0]);
            return ((APIResultOfString)(results[0]));
        }
        
        /// <remarks/>
        public void PingAsync() {
            this.PingAsync(null);
        }
        
        /// <remarks/>
        public void PingAsync(object userState) {
            if ((this.PingOperationCompleted == null)) {
                this.PingOperationCompleted = new System.Threading.SendOrPostCallback(this.OnPingOperationCompleted);
            }
            this.InvokeAsync("Ping", new object[0], this.PingOperationCompleted, userState);
        }
        
        private void OnPingOperationCompleted(object arg) {
            if ((this.PingCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.PingCompleted(this, new PingCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2046.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://api.channeladvisor.com/webservices/")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://api.channeladvisor.com/webservices/", IsNullable=false)]
    public partial class APICredentials : System.Web.Services.Protocols.SoapHeader {
        
        private string developerKeyField;
        
        private string passwordField;
        
        private System.Xml.XmlAttribute[] anyAttrField;
        
        /// <remarks/>
        public string DeveloperKey {
            get {
                return this.developerKeyField;
            }
            set {
                this.developerKeyField = value;
            }
        }
        
        /// <remarks/>
        public string Password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2046.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://api.channeladvisor.com/webservices/")]
    public partial class APIResultOfString {
        
        private ResultStatus statusField;
        
        private int messageCodeField;
        
        private string messageField;
        
        private string dataField;
        
        private string resultDataField;
        
        /// <remarks/>
        public ResultStatus Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        public int MessageCode {
            get {
                return this.messageCodeField;
            }
            set {
                this.messageCodeField = value;
            }
        }
        
        /// <remarks/>
        public string Message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
            }
        }
        
        /// <remarks/>
        public string Data {
            get {
                return this.dataField;
            }
            set {
                this.dataField = value;
            }
        }
        
        /// <remarks/>
        public string ResultData {
            get {
                return this.resultDataField;
            }
            set {
                this.resultDataField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2046.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://api.channeladvisor.com/webservices/")]
    public enum ResultStatus {
        
        /// <remarks/>
        Success,
        
        /// <remarks/>
        Failure,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2046.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://api.channeladvisor.com/webservices/")]
    public partial class FulfillmentItemMoveResponse {
        
        private int fulfillmentItemIDField;
        
        private bool successField;
        
        private string messageField;
        
        /// <remarks/>
        public int FulfillmentItemID {
            get {
                return this.fulfillmentItemIDField;
            }
            set {
                this.fulfillmentItemIDField = value;
            }
        }
        
        /// <remarks/>
        public bool Success {
            get {
                return this.successField;
            }
            set {
                this.successField = value;
            }
        }
        
        /// <remarks/>
        public string Message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2046.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://api.channeladvisor.com/webservices/")]
    public partial class APIResultOfArrayOfFulfillmentItemMoveResponse {
        
        private ResultStatus statusField;
        
        private int messageCodeField;
        
        private string messageField;
        
        private string dataField;
        
        private FulfillmentItemMoveResponse[] resultDataField;
        
        /// <remarks/>
        public ResultStatus Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        public int MessageCode {
            get {
                return this.messageCodeField;
            }
            set {
                this.messageCodeField = value;
            }
        }
        
        /// <remarks/>
        public string Message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
            }
        }
        
        /// <remarks/>
        public string Data {
            get {
                return this.dataField;
            }
            set {
                this.dataField = value;
            }
        }
        
        /// <remarks/>
        public FulfillmentItemMoveResponse[] ResultData {
            get {
                return this.resultDataField;
            }
            set {
                this.resultDataField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2046.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://api.channeladvisor.com/webservices/")]
    public partial class FulfillmentItemSubmit {
        
        private int fulfillmentItemIDField;
        
        private int quantityField;
        
        /// <remarks/>
        public int FulfillmentItemID {
            get {
                return this.fulfillmentItemIDField;
            }
            set {
                this.fulfillmentItemIDField = value;
            }
        }
        
        /// <remarks/>
        public int Quantity {
            get {
                return this.quantityField;
            }
            set {
                this.quantityField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2046.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://api.channeladvisor.com/webservices/")]
    public partial class FulfillmentCreateSubmit {
        
        private string fulfillmentTypeField;
        
        private string fulfillmentStatusField;
        
        private string carrierCodeField;
        
        private string classCodeField;
        
        private string trackingNumberField;
        
        private string distributionCenterCodeField;
        
        private System.Nullable<decimal> costField;
        
        private System.Nullable<decimal> taxCostField;
        
        private System.Nullable<decimal> insuranceCostField;
        
        private System.Nullable<System.DateTime> shippedDateGMTField;
        
        private string sellerFulfillmentIDField;
        
        private FulfillmentItemSubmit[] itemListField;
        
        /// <remarks/>
        public string FulfillmentType {
            get {
                return this.fulfillmentTypeField;
            }
            set {
                this.fulfillmentTypeField = value;
            }
        }
        
        /// <remarks/>
        public string FulfillmentStatus {
            get {
                return this.fulfillmentStatusField;
            }
            set {
                this.fulfillmentStatusField = value;
            }
        }
        
        /// <remarks/>
        public string CarrierCode {
            get {
                return this.carrierCodeField;
            }
            set {
                this.carrierCodeField = value;
            }
        }
        
        /// <remarks/>
        public string ClassCode {
            get {
                return this.classCodeField;
            }
            set {
                this.classCodeField = value;
            }
        }
        
        /// <remarks/>
        public string TrackingNumber {
            get {
                return this.trackingNumberField;
            }
            set {
                this.trackingNumberField = value;
            }
        }
        
        /// <remarks/>
        public string DistributionCenterCode {
            get {
                return this.distributionCenterCodeField;
            }
            set {
                this.distributionCenterCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<decimal> Cost {
            get {
                return this.costField;
            }
            set {
                this.costField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<decimal> TaxCost {
            get {
                return this.taxCostField;
            }
            set {
                this.taxCostField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<decimal> InsuranceCost {
            get {
                return this.insuranceCostField;
            }
            set {
                this.insuranceCostField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> ShippedDateGMT {
            get {
                return this.shippedDateGMTField;
            }
            set {
                this.shippedDateGMTField = value;
            }
        }
        
        /// <remarks/>
        public string SellerFulfillmentID {
            get {
                return this.sellerFulfillmentIDField;
            }
            set {
                this.sellerFulfillmentIDField = value;
            }
        }
        
        /// <remarks/>
        public FulfillmentItemSubmit[] ItemList {
            get {
                return this.itemListField;
            }
            set {
                this.itemListField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2046.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://api.channeladvisor.com/webservices/")]
    public partial class FulfillmentOperationResponse {
        
        private int fulfillmentIDField;
        
        private bool successField;
        
        private string messageField;
        
        /// <remarks/>
        public int FulfillmentID {
            get {
                return this.fulfillmentIDField;
            }
            set {
                this.fulfillmentIDField = value;
            }
        }
        
        /// <remarks/>
        public bool Success {
            get {
                return this.successField;
            }
            set {
                this.successField = value;
            }
        }
        
        /// <remarks/>
        public string Message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2046.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://api.channeladvisor.com/webservices/")]
    public partial class APIResultOfArrayOfFulfillmentOperationResponse {
        
        private ResultStatus statusField;
        
        private int messageCodeField;
        
        private string messageField;
        
        private string dataField;
        
        private FulfillmentOperationResponse[] resultDataField;
        
        /// <remarks/>
        public ResultStatus Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        public int MessageCode {
            get {
                return this.messageCodeField;
            }
            set {
                this.messageCodeField = value;
            }
        }
        
        /// <remarks/>
        public string Message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
            }
        }
        
        /// <remarks/>
        public string Data {
            get {
                return this.dataField;
            }
            set {
                this.dataField = value;
            }
        }
        
        /// <remarks/>
        public FulfillmentOperationResponse[] ResultData {
            get {
                return this.resultDataField;
            }
            set {
                this.resultDataField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2046.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://api.channeladvisor.com/webservices/")]
    public partial class FulfillmentUpdateSubmit {
        
        private int fulfillmentIDField;
        
        private string fulfillmentTypeField;
        
        private string fulfillmentStatusField;
        
        private string carrierCodeField;
        
        private string classCodeField;
        
        private string trackingNumberField;
        
        private System.Nullable<decimal> costField;
        
        private System.Nullable<decimal> taxCostField;
        
        private System.Nullable<decimal> insuranceCostField;
        
        private System.Nullable<System.DateTime> shippedDateGMTField;
        
        private string sellerFulfillmentIDField;
        
        /// <remarks/>
        public int FulfillmentID {
            get {
                return this.fulfillmentIDField;
            }
            set {
                this.fulfillmentIDField = value;
            }
        }
        
        /// <remarks/>
        public string FulfillmentType {
            get {
                return this.fulfillmentTypeField;
            }
            set {
                this.fulfillmentTypeField = value;
            }
        }
        
        /// <remarks/>
        public string FulfillmentStatus {
            get {
                return this.fulfillmentStatusField;
            }
            set {
                this.fulfillmentStatusField = value;
            }
        }
        
        /// <remarks/>
        public string CarrierCode {
            get {
                return this.carrierCodeField;
            }
            set {
                this.carrierCodeField = value;
            }
        }
        
        /// <remarks/>
        public string ClassCode {
            get {
                return this.classCodeField;
            }
            set {
                this.classCodeField = value;
            }
        }
        
        /// <remarks/>
        public string TrackingNumber {
            get {
                return this.trackingNumberField;
            }
            set {
                this.trackingNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<decimal> Cost {
            get {
                return this.costField;
            }
            set {
                this.costField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<decimal> TaxCost {
            get {
                return this.taxCostField;
            }
            set {
                this.taxCostField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<decimal> InsuranceCost {
            get {
                return this.insuranceCostField;
            }
            set {
                this.insuranceCostField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> ShippedDateGMT {
            get {
                return this.shippedDateGMTField;
            }
            set {
                this.shippedDateGMTField = value;
            }
        }
        
        /// <remarks/>
        public string SellerFulfillmentID {
            get {
                return this.sellerFulfillmentIDField;
            }
            set {
                this.sellerFulfillmentIDField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2046.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://api.channeladvisor.com/webservices/")]
    public partial class FulfillmentItemDetailResponse {
        
        private int fulfillmentItemIDField;
        
        private string sKUField;
        
        private int quantityField;
        
        private int lineItemIDField;
        
        private string siteAuctionIDField;
        
        private string saleSourceIDField;
        
        /// <remarks/>
        public int FulfillmentItemID {
            get {
                return this.fulfillmentItemIDField;
            }
            set {
                this.fulfillmentItemIDField = value;
            }
        }
        
        /// <remarks/>
        public string SKU {
            get {
                return this.sKUField;
            }
            set {
                this.sKUField = value;
            }
        }
        
        /// <remarks/>
        public int Quantity {
            get {
                return this.quantityField;
            }
            set {
                this.quantityField = value;
            }
        }
        
        /// <remarks/>
        public int LineItemID {
            get {
                return this.lineItemIDField;
            }
            set {
                this.lineItemIDField = value;
            }
        }
        
        /// <remarks/>
        public string SiteAuctionID {
            get {
                return this.siteAuctionIDField;
            }
            set {
                this.siteAuctionIDField = value;
            }
        }
        
        /// <remarks/>
        public string SaleSourceID {
            get {
                return this.saleSourceIDField;
            }
            set {
                this.saleSourceIDField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2046.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://api.channeladvisor.com/webservices/")]
    public partial class FulfillmentDetailResponse {
        
        private int fulfillmentIDField;
        
        private System.DateTime createdDateGMTField;
        
        private System.DateTime updatedDateGMTField;
        
        private string fulfillmentTypeField;
        
        private string fulfillmentStatusField;
        
        private string carrierCodeField;
        
        private string classCodeField;
        
        private string trackingNumberField;
        
        private string distributionCenterCodeField;
        
        private System.Nullable<decimal> costField;
        
        private System.Nullable<decimal> taxCostField;
        
        private System.Nullable<decimal> insuranceCostField;
        
        private System.Nullable<System.DateTime> shippedDateGMTField;
        
        private string sellerFulfillmentIDField;
        
        private FulfillmentItemDetailResponse[] itemListField;
        
        /// <remarks/>
        public int FulfillmentID {
            get {
                return this.fulfillmentIDField;
            }
            set {
                this.fulfillmentIDField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime CreatedDateGMT {
            get {
                return this.createdDateGMTField;
            }
            set {
                this.createdDateGMTField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime UpdatedDateGMT {
            get {
                return this.updatedDateGMTField;
            }
            set {
                this.updatedDateGMTField = value;
            }
        }
        
        /// <remarks/>
        public string FulfillmentType {
            get {
                return this.fulfillmentTypeField;
            }
            set {
                this.fulfillmentTypeField = value;
            }
        }
        
        /// <remarks/>
        public string FulfillmentStatus {
            get {
                return this.fulfillmentStatusField;
            }
            set {
                this.fulfillmentStatusField = value;
            }
        }
        
        /// <remarks/>
        public string CarrierCode {
            get {
                return this.carrierCodeField;
            }
            set {
                this.carrierCodeField = value;
            }
        }
        
        /// <remarks/>
        public string ClassCode {
            get {
                return this.classCodeField;
            }
            set {
                this.classCodeField = value;
            }
        }
        
        /// <remarks/>
        public string TrackingNumber {
            get {
                return this.trackingNumberField;
            }
            set {
                this.trackingNumberField = value;
            }
        }
        
        /// <remarks/>
        public string DistributionCenterCode {
            get {
                return this.distributionCenterCodeField;
            }
            set {
                this.distributionCenterCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<decimal> Cost {
            get {
                return this.costField;
            }
            set {
                this.costField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<decimal> TaxCost {
            get {
                return this.taxCostField;
            }
            set {
                this.taxCostField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<decimal> InsuranceCost {
            get {
                return this.insuranceCostField;
            }
            set {
                this.insuranceCostField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> ShippedDateGMT {
            get {
                return this.shippedDateGMTField;
            }
            set {
                this.shippedDateGMTField = value;
            }
        }
        
        /// <remarks/>
        public string SellerFulfillmentID {
            get {
                return this.sellerFulfillmentIDField;
            }
            set {
                this.sellerFulfillmentIDField = value;
            }
        }
        
        /// <remarks/>
        public FulfillmentItemDetailResponse[] ItemList {
            get {
                return this.itemListField;
            }
            set {
                this.itemListField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2046.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://api.channeladvisor.com/webservices/")]
    public partial class OrderFulfillmentResponse {
        
        private int orderIDField;
        
        private string clientOrderIdentifierField;
        
        private FulfillmentDetailResponse[] fulfillmentListField;
        
        /// <remarks/>
        public int OrderID {
            get {
                return this.orderIDField;
            }
            set {
                this.orderIDField = value;
            }
        }
        
        /// <remarks/>
        public string ClientOrderIdentifier {
            get {
                return this.clientOrderIdentifierField;
            }
            set {
                this.clientOrderIdentifierField = value;
            }
        }
        
        /// <remarks/>
        public FulfillmentDetailResponse[] FulfillmentList {
            get {
                return this.fulfillmentListField;
            }
            set {
                this.fulfillmentListField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2046.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://api.channeladvisor.com/webservices/")]
    public partial class APIResultOfArrayOfOrderFulfillmentResponse {
        
        private ResultStatus statusField;
        
        private int messageCodeField;
        
        private string messageField;
        
        private string dataField;
        
        private OrderFulfillmentResponse[] resultDataField;
        
        /// <remarks/>
        public ResultStatus Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        public int MessageCode {
            get {
                return this.messageCodeField;
            }
            set {
                this.messageCodeField = value;
            }
        }
        
        /// <remarks/>
        public string Message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
            }
        }
        
        /// <remarks/>
        public string Data {
            get {
                return this.dataField;
            }
            set {
                this.dataField = value;
            }
        }
        
        /// <remarks/>
        public OrderFulfillmentResponse[] ResultData {
            get {
                return this.resultDataField;
            }
            set {
                this.resultDataField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void GetOrderFulfillmentDetailListCompletedEventHandler(object sender, GetOrderFulfillmentDetailListCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetOrderFulfillmentDetailListCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetOrderFulfillmentDetailListCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public APIResultOfArrayOfOrderFulfillmentResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((APIResultOfArrayOfOrderFulfillmentResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void UpdateOrderFulfillmentsCompletedEventHandler(object sender, UpdateOrderFulfillmentsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UpdateOrderFulfillmentsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UpdateOrderFulfillmentsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public APIResultOfArrayOfFulfillmentOperationResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((APIResultOfArrayOfFulfillmentOperationResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void CreateOrderFulfillmentsCompletedEventHandler(object sender, CreateOrderFulfillmentsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CreateOrderFulfillmentsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CreateOrderFulfillmentsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public APIResultOfArrayOfFulfillmentOperationResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((APIResultOfArrayOfFulfillmentOperationResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void MoveFulfillmentItemsCompletedEventHandler(object sender, MoveFulfillmentItemsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class MoveFulfillmentItemsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal MoveFulfillmentItemsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public APIResultOfArrayOfFulfillmentItemMoveResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((APIResultOfArrayOfFulfillmentItemMoveResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void PingCompletedEventHandler(object sender, PingCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class PingCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal PingCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public APIResultOfString Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((APIResultOfString)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591