//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChannelAdvisorSOAP.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.1.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://api.channeladvisor.com/ChannelAdvisorAPI/v7/InventoryService.asmx")]
        public string ChannelAdvisorSOAP_CA_InventoryService_InventoryService {
            get {
                return ((string)(this["ChannelAdvisorSOAP_CA_InventoryService_InventoryService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://api.channeladvisor.com/ChannelAdvisorAPI/v7/AdminService.asmx")]
        public string ChannelAdvisorSOAP_CA_AdminService_AdminService {
            get {
                return ((string)(this["ChannelAdvisorSOAP_CA_AdminService_AdminService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://api.channeladvisor.com/ChannelAdvisorAPI/v7/OrderService.asmx")]
        public string ChannelAdvisorSOAP_Orders_OrderService {
            get {
                return ((string)(this["ChannelAdvisorSOAP_Orders_OrderService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://api.channeladvisor.com/ChannelAdvisorAPI/V7/FulfillmentService.asmx")]
        public string ChannelAdvisorSOAP_Fulfillment_FulfillmentService {
            get {
                return ((string)(this["ChannelAdvisorSOAP_Fulfillment_FulfillmentService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1200000")]
        public int ChannelAdvisorSOAP_Timeout {
            get {
                return ((int)(this["ChannelAdvisorSOAP_Timeout"]));
            }
        }
    }
}
